/// Flutter icons LastIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LastIcon
///      fonts:
///       - asset: fonts/LastIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LastIcon {
  LastIcon._();

  static const _kFontFam = 'LastIcon';
  static const _kFontPkg = null;

  static const IconData vege = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData area = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inventory = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mature = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repro = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ripen = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expense = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
