/// Flutter icons PlatIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlatIcon
///      fonts:
///       - asset: fonts/PlatIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlatIcon {
  PlatIcon._();

  static const _kFontFam = 'PlatIcon';
  static const _kFontPkg = null;

  static const IconData calendar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pesticide_black = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spraying_white = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expenses = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shovel = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inventory = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
